import lifeStyleProfile1 from '@/assets/image/lifeStyle-profile1.png';
import lifeStyleProfile2 from '@/assets/image/lifeStyle-profile2.png';
import lifeStyleProfile3 from '@/assets/image/lifeStyle-profile3.png';
import lifeStyleProfile4 from '@/assets/image/lifeStyle-profile4.png';

import Exclusive from '@/assets/image/Exclusive.png';
import LeBlanc from '@/assets/image/LeBlanc.png';
import Prestige from '@/assets/image/Prestige.png';
import Calligraphy from '@/assets/image/Calligraphy.png';
import basicWheel from '@/assets/icon/Basic-wheel.svg';
import alloyWheel from '@/assets/icon/Alloy-wheel.svg';
import sheet from '@/assets/icon/Sheet.svg';
import navigation from '@/assets/icon/Navigation.svg';
import cluster from '@/assets/icon/Cluster.svg';

import Abyss from '@/assets/image/exterior-abyss.png';
import Shimmering from '@/assets/image/exterior-shimmering.png';
import Moonlight from '@/assets/image/exterior-moonlight.png';
import Gaia from '@/assets/image/exterior-gaia.png';
import Graphite from '@/assets/image/exterior-graphite.png';
import Creamy from '@/assets/image/exterior-creamy.png';
import Quilted from '@/assets/image/interior-quilted.png';
import Robust from '@/assets/image/exterior-robust.png';
import CoolGray from '@/assets/image/interior-coolgray.png';
import Black from '@/assets/image/interior-black.png';
import Navy from '@/assets/image/interior-navy.png';
import SyntheticBlack from '@/assets/image/interior-synthetic_black.png';
import Burgundy from '@/assets/image/interior-burgundy.png';
import NavyWarmGray from '@/assets/image/interior-navy_warmgray.png';
import PremiumBlack from '@/assets/image/interior-premium_black.png';
import OneToneBlack from '@/assets/image/interior-onetone_balck.png';
import Brown from '@/assets/image/interior-brown.png';

export const ageQuestionList = ['20대', '30대', '40대', '50대 이상'];
export const lifeStyleQuestionList = [
  {
    value: '1',
    tags: ['#주행안전', '#사용편의'],
    description: '가족과 함께 타서\n안전을 중시해요.',
    profileImage: lifeStyleProfile1,
  },
  {
    value: '2',
    tags: ['#사용편의', '#추위/더위'],
    description: '매일 출퇴근하여 경제적이고\n편안한 주행을 원해요.',
    profileImage: lifeStyleProfile2,
  },
  {
    value: '3',
    tags: ['#주행안전', '#주차/출차'],
    description: '운전 경력이 짧아\n똑똑한 주행을 원해요.',
    profileImage: lifeStyleProfile3,
  },
  {
    value: '4',
    tags: ['#스타일', '#퍼포먼스'],
    description: '트렌드에 민감해\n디자인과 성능이 중요해요.',
    profileImage: lifeStyleProfile4,
  },
];

export const lifeStyleAdditionQuestionList = [
  {
    value: 'drivingExperience',
    question: '운전 경력이 어떻게 되시나요?',
    answerList: ['1년 이하', '1년 이상 ~ 5년 미만', '5년 이상'],
  },
  {
    value: 'numberOfFamilyMembers',
    question: '가족 구성원이 몇 명인가요?',
    answerList: ['1인', '2인', '3-4인', '5인 이상'],
  },
  {
    value: 'purpose',
    question: '어떤 목적으로 주로 차를 타시나요?',
    answerList: ['출퇴근용', '레저용', '가정용', '업무용'],
  },
  {
    value: 'lifeValue',
    question: '자동차를 살 때 어떤 가치가 가장 중요한가요?',
    answerList: ['디자인', '성능', '안전', '편의성'],
  },
];

export const price = {
  lowestPrice: 4200,
  highestPrice: 6900,
  rangeUnit: 300,
  priceUnit: '만원',
};

export const carFeatureList = [
  {
    type: 'engine',
    description: '엔진',
    valueList: ['디젤 2.2', '가솔린 3.8'],
  },
  {
    type: 'body',
    description: '바디',
    valueList: ['7인승', '8인승'],
  },
  {
    type: 'drivingSystem',
    description: '구동방식',
    valueList: ['2WD', '4WD'],
  },
];

export const carSpecData = [
  {
    car_spec_id: 1,
    trim_id: 1,
    trim_name: 'Exclusive',
    price: 43460100,
    summary: '합리적인 당신을 위한',
    basic_option_ids: [1, 2, 3],
    basic_option_names: [
      '12인치 내비게이션',
      '내비 기반 크루즈 컨트롤',
      '세이프티 파워 윈도우',
    ],
  },
  {
    car_spec_id: 2,
    trim_id: 2,
    trim_name: 'Le Blanc',
    price: 43460200,
    summary: '필수적인 옵션만 모은',
    basic_option_ids: [4, 5, 6],
    basic_option_names: [
      '20인치 알로이 휠',
      '12인치 클러스터',
      '서라운드 뷰 모니터',
    ],
  },
  {
    car_spec_id: 3,
    trim_id: 3,
    trim_name: 'Prestige',
    price: 43460300,
    summary: '가치있는 드라이빙 경험을 주는',
    basic_option_ids: [7, 8, 9],
    basic_option_names: [
      '2열 통풍시트',
      '스마트 자세제어',
      '2열 수동식 도어 커튼',
    ],
  },
  {
    car_spec_id: 4,
    trim_id: 4,
    trim_name: 'Caligraphy',
    price: 43460400,
    summary: '남들과 차별화된 경험',
    basic_option_ids: [10, 11, 12],
    basic_option_names: [
      '20인치 캘리그라피 전용 휠',
      'KRELL 프리미엄 사운드',
      '블랙 에디션',
    ],
  },
];

export const trimCompareData = [
  {
    carImage: Exclusive,
    forYou: '합리적인 당신을 위한',
    trimName: 'Exclusive',
    price: '₩40,440,000',
    exteriorColor: [
      '#121212',
      '#979999',
      '#171D2F',
      '#292622',
      '#313433',
      '#F2F4F3',
    ],
    interiorColor: '인조가죽(블랙)',
    wheelImage: basicWheel,
    wheelSize: '18 inch',
    wheelName: '기본 휠',
    sheetImage: sheet,
    sheetName: '인조/천연가죽 시트',
    navigationImage: navigation,
    navigationSize: '12.3 inch',
    navigationName: '네비게이션',
    clusterImage: cluster,
    clusterSize: '4.2 inch',
    clusterName: '클러스터',
    basicOption: [
      '전방 충돌 방지 보조',
      '내비 기반 크루즈 컨트롤',
      '세이프티 파워 윈도우',
    ],
  },
  {
    carImage: LeBlanc,
    forYou: '필수적인 옵션만 모은',
    trimName: 'Le Blanc',
    price: '₩43,460,000',
    exteriorColor: [
      '#121212',
      '#979999',
      '#171D2F',
      '#292622',
      '#313433',
      '#F2F4F3',
    ],
    interiorColor: '쿨그레이 퀄팅천연(블랙)',
    wheelImage: alloyWheel,
    wheelSize: '20 inch',
    wheelName: '알로이 휠',
    sheetImage: sheet,
    sheetName: '퀼팅 천연가죽 시트',
    navigationImage: navigation,
    navigationSize: '12.3 inch',
    navigationName: '네비게이션',
    clusterImage: cluster,
    clusterSize: '12.3 inch',
    clusterName: '클러스터',
    basicOption: [
      '퀼팅 천연가죽 시트',
      '12인치 클러스터',
      '서라운드 뷰 모니터',
    ],
  },
  {
    carImage: Prestige,
    forYou: '가치있는 드라이빙을 위한',
    trimName: 'Prestige',
    price: '₩47,720,000',
    exteriorColor: [
      '#121212',
      '#979999',
      '#171D2F',
      '#292622',
      '#313433',
      '#F2F4F3',
    ],
    interiorColor: '네이비 블랙 버건디',
    wheelImage: alloyWheel,
    wheelSize: '20 inch',
    wheelName: '알로이 휠',
    sheetImage: sheet,
    sheetName: '퀼팅 나파가죽 시트',
    navigationImage: navigation,
    navigationSize: '12.3 inch',
    navigationName: '네비게이션',
    clusterImage: cluster,
    clusterSize: '12.3 inch',
    clusterName: '클러스터',
    basicOption: ['2열 통풍시트', '스마트 자세제어', '2열 수동식 도어 커튼'],
  },
  {
    carImage: Calligraphy,
    forYou: '남들과 차별화된 경험',
    trimName: 'Calligraphy',
    price: '₩52,540,000',
    exteriorColor: [
      '#121212',
      '#A1A3A2',
      '#142419',
      '#181F30',
      '#2C2925',
      '#3C3F3E',
      '#F1F2F3',
    ],
    interiorColor: '블랙(고급) 브라운',
    interiorColor2: '블랙 원톤(블랙에디션 전용)',
    wheelImage: alloyWheel,
    wheelSize: '20 inch',
    wheelName: '캘리그라피 전용 휠',
    sheetImage: sheet,
    sheetName: '퀼팅 나파가죽 시트 (캘리그라피 전용)',
    navigationImage: navigation,
    navigationSize: '12.3 inch',
    navigationName: '네비게이션',
    clusterImage: cluster,
    clusterSize: '12.3 inch',
    clusterName: '클러스터',
    basicOption: [
      '20인치 캘리그라피 전용 휠',
      'KRELL 프리미엄 사운드',
      '블랙 에디션',
    ],
  },
];

export const allColorData = {
  1: {
    exteriorColors: {
      availableColors: {
        1: {
          name: '크리미 화이트 펄',
          imgUrl: '/assets/image/exterior-creamy.png',
          carImgUrls: '/palisade/white/image_',
          price: 100000,
          chooseRate: 80,
        },
        2: {
          name: '어비스 블랙펄',
          imgUrl: '/assets/image/exterior-abyss.png',
          carImgUrls: '/palisade/abyss/image_',
          price: 0,
          chooseRate: 70,
        },
        3: {
          name: '쉬머링 실버 메탈릭',
          imgUrl: '/assets/image/exterior-shimmering.png',
          carImgUrls: '/palisade/silver/image_',
          price: 0,
          chooseRate: 60,
        },
        4: {
          name: '문라이트 블루 펄',
          imgUrl: '/assets/image/exterior-moonlight.png',
          carImgUrls: '/palisade/blue/image_',
          price: 0,
          chooseRate: 50,
        },
        5: {
          name: '가이아 브라운 펄',
          imgUrl: '/assets/image/exterior-gaia.png',
          carImgUrls: '/palisade/brown/image_',
          price: 0,
          chooseRate: 40,
        },
        6: {
          name: '그라파이트 그레이 메탈릭',
          imgUrl: '/assets/image/exterior-graphite.png',
          carImgUrls: '/palisade/gray/image_',
          price: 0,
          chooseRate: 30,
        },
      },
      unAvailableColors: {},
      otherTrimColors: {
        7: {
          name: '로버스트 에메랄드 펄',
          imgUrl: '/assets/image/exterior-robust.png',
          carImgUrls: '/palisade/robust/image_',
          price: 40000,
          chooseRate: 70,
        },
      },
    },
    interiorColors: {
      availableColors: {
        1: {
          name: '퀄팅 천연(블랙)',
          imgUrl: '/assets/image/interior-quilted.png',
          carImgUrls: '',
          price: 50000,
          chooseRate: 70,
        },
        2: {
          name: '쿨 그레이',
          imgUrl: '/assets/image/interior-coolgray.png',
          carImgUrls: '',
          price: 70000,
          chooseRate: 60,
        },
      },
      unAvailableColors: {},
      otherTrimColors: {
        3: {
          name: '인조가죽(블랙)',
          imgUrl: '/assets/image/interior-articifial-leather-black.png',
          carImgUrls: '',
          price: 0,
          chooseRate: 70,
        },
        4: {
          name: '네이비',
          imgUrl: '/assets/image/interior-navy.png',
          carImgUrls: '',
          price: 0,
          chooseRate: 60,
        },
        5: {
          name: '블랙',
          imgUrl: '/assets/image/interior-black.png',
          carImgUrls: '',
          price: 0,
          chooseRate: 50,
        },
        6: {
          name: '버건디',
          imgUrl: '/assets/image/interior-burgundy.png',
          carImgUrls: '',
          price: 0,
          chooseRate: 40,
        },
        7: {
          name: '네이비/웜그레이 투톤',
          imgUrl: '/assets/image/interior-navy_warmgray.png',
          carImgUrls: '',
          price: 0,
          chooseRate: 30,
        },
        8: {
          name: '블랙(고급)',
          imgUrl: '/assets/image/interior-premium_black.png',
          carImgUrls: '',
          price: 0,
          chooseRate: 20,
        },
        9: {
          name: '블랙원톤(블랙에디션전용)',
          imgUrl: '/assets/image/interior-onetone_black.png',
          carImgUrls: '',
          price: 0,
          chooseRate: 10,
        },
        10: {
          name: '브라운',
          imgUrl: '/assets/image/interior-brown.png',
          carImgUrls: '',
          price: 0,
          chooseRate: 5,
        },
      },
    },
  },

  2: {
    exteriorColors: {
      availableColors: {
        1: {
          name: '크리미 화이트 펄',
          imgUrl: '/assets/image/exterior-creamy.png',
          carImgUrls: '/palisade/white/image_',
          price: 100000,
          chooseRate: 80,
        },
        2: {
          name: '어비스 블랙펄',
          imgUrl: '/assets/image/exterior-abyss.png',
          carImgUrls: '/palisade/abyss/image_',
          price: 0,
          chooseRate: 70,
        },
        3: {
          name: '쉬머링 실버 메탈릭',
          imgUrl: '/assets/image/exterior-shimmering.png',
          carImgUrls: '/palisade/silver/image_',
          price: 0,
          chooseRate: 60,
        },
        4: {
          name: '문라이트 블루 펄',
          imgUrl: '/assets/image/exterior-moonlight.png',
          carImgUrls: '/palisade/blue/image_',
          price: 0,
          chooseRate: 50,
        },
        5: {
          name: '가이아 브라운 펄',
          imgUrl: '/assets/image/exterior-gaia.png',
          carImgUrls: '/palisade/brown/image_',
          price: 0,
          chooseRate: 40,
        },
        6: {
          name: '그라파이트 그레이 메탈릭',
          imgUrl: '/assets/image/exterior-graphite.png',
          carImgUrls: '/palisade/gray/image_',
          price: 0,
          chooseRate: 30,
        },
      },
      unAvailableColors: {},
      otherTrimColors: {
        7: {
          name: '로버스트 에메랄드 펄',
          imgUrl: '/assets/image/exterior-robust.png',
          carImgUrls: '/palisade/robust/image_',
          price: 40000,
          chooseRate: 70,
        },
      },
    },
    interiorColors: {
      availableColors: {
        3: {
          name: '인조가죽(블랙)',
          imgUrl: '/assets/image/interior-synthtic_black.png',
          carImgUrls: '',
          price: 50000,
          chooseRate: 40,
        },
      },
      unAvailableColors: {},
      otherTrimColors: {
        1: {
          name: '퀄팅 천연(블랙)',
          imgUrl: '/assets/image/interior-quilted.png',
          carImgUrls: '',
          price: 50000,
          chooseRate: 70,
        },
        2: {
          name: '쿨 그레이',
          imgUrl: '/assets/image/interior-coolgray.png',
          carImgUrls: '',
          price: 70000,
          chooseRate: 60,
        },
        4: {
          name: '네이비',
          imgUrl: '/assets/image/interior-navy.png',
          carImgUrls: '',
          price: 0,
          chooseRate: 60,
        },
        5: {
          name: '블랙',
          imgUrl: '/assets/image/interior-black.png',
          carImgUrls: '',
          price: 0,
          chooseRate: 50,
        },
        6: {
          name: '버건디',
          imgUrl: '/assets/image/interior-burgundy.png',
          carImgUrls: '',
          price: 0,
          chooseRate: 40,
        },
        7: {
          name: '네이비/웜그레이 투톤',
          imgUrl: '/assets/image/interior-navy_warmgray.png',
          carImgUrls: '',
          price: 0,
          chooseRate: 30,
        },
        8: {
          name: '블랙(고급)',
          imgUrl: '/assets/image/interior-premium_black.png',
          carImgUrls: '',
          price: 0,
          chooseRate: 20,
        },
        9: {
          name: '블랙원톤(블랙에디션전용)',
          imgUrl: '/assets/image/interior-onetone_black.png',
          carImgUrls: '',
          price: 0,
          chooseRate: 10,
        },
        10: {
          name: '브라운',
          imgUrl: '/assets/image/interior-brown.png',
          carImgUrls: '',
          price: 0,
          chooseRate: 5,
        },
      },
    },
  },

  3: {
    exteriorColors: {
      availableColors: {
        1: {
          name: '크리미 화이트 펄',
          imgUrl: '/assets/image/exterior-creamy.png',
          carImgUrls: '/palisade/white/image_',
          price: 100000,
          chooseRate: 80,
        },
        2: {
          name: '어비스 블랙펄',
          imgUrl: '/assets/image/exterior-abyss.png',
          carImgUrls: '/palisade/abyss/image_',
          price: 0,
          chooseRate: 70,
        },
        3: {
          name: '쉬머링 실버 메탈릭',
          imgUrl: '/assets/image/exterior-shimmering.png',
          carImgUrls: '/palisade/silver/image_',
          price: 0,
          chooseRate: 60,
        },
        4: {
          name: '문라이트 블루 펄',
          imgUrl: '/assets/image/exterior-moonlight.png',
          carImgUrls: '/palisade/blue/image_',
          price: 0,
          chooseRate: 50,
        },
        5: {
          name: '가이아 브라운 펄',
          imgUrl: '/assets/image/exterior-gaia.png',
          carImgUrls: '/palisade/brown/image_',
          price: 0,
          chooseRate: 40,
        },
        6: {
          name: '그라파이트 그레이 메탈릭',
          imgUrl: '/assets/image/exterior-graphite.png',
          carImgUrls: '/palisade/gray/image_',
          price: 0,
          chooseRate: 30,
        },
      },
      unAvailableColors: {},
      otherTrimColors: {
        7: {
          name: '로버스트 에메랄드 펄',
          imgUrl: '/assets/image/exterior-robust.png',
          carImgUrls: '/palisade/robust/image_',
          price: 40000,
          chooseRate: 70,
        },
      },
    },
    interiorColors: {
      availableColors: {
        4: {
          name: '네이비',
          imgUrl: '/assets/image/interior-navy.png',
          carImgUrls: '',
          price: 0,
          chooseRate: 60,
        },
        5: {
          name: '블랙',
          imgUrl: '/assets/image/interior-black.png',
          carImgUrls: '',
          price: 0,
          chooseRate: 50,
        },
        6: {
          name: '버건디',
          imgUrl: '/assets/image/interior-burgundy.png',
          carImgUrls: '',
          price: 0,
          chooseRate: 40,
        },
      },
      unAvailableColors: {},
      otherTrimColors: {
        1: {
          name: '퀄팅 천연(블랙)',
          imgUrl: '/assets/image/interior-quilted.png',
          carImgUrls: '',
          price: 50000,
          chooseRate: 70,
        },
        2: {
          name: '쿨 그레이',
          imgUrl: '/assets/image/interior-coolgray.png',
          carImgUrls: '',
          price: 70000,
          chooseRate: 60,
        },
        3: {
          name: '인조가죽(블랙)',
          imgUrl: '/assets/image/interior-synthtic_black.png',
          carImgUrls: '',
          price: 50000,
          chooseRate: 40,
        },
        7: {
          name: '네이비/웜그레이 투톤',
          imgUrl: '/assets/image/interior-navy_warmgray.png',
          carImgUrls: '',
          price: 0,
          chooseRate: 30,
        },
        8: {
          name: '블랙(고급)',
          imgUrl: '/assets/image/interior-premium_black.png',
          carImgUrls: '',
          price: 0,
          chooseRate: 20,
        },
        9: {
          name: '블랙원톤(블랙에디션전용)',
          imgUrl: '/assets/image/interior-onetone_black.png',
          carImgUrls: '',
          price: 0,
          chooseRate: 10,
        },
        10: {
          name: '브라운',
          imgUrl: '/assets/image/interior-brown.png',
          carImgUrls: '',
          price: 0,
          chooseRate: 5,
        },
      },
    },
  },

  4: {
    exteriorColors: {
      availableColors: {
        1: {
          name: '크리미 화이트 펄',
          imgUrl: '/assets/image/exterior-creamy.png',
          carImgUrls: '/palisade/white/image_',
          price: 100000,
          chooseRate: 80,
        },
        2: {
          name: '어비스 블랙펄',
          imgUrl: '/assets/image/exterior-abyss.png',
          carImgUrls: '/palisade/abyss/image_',
          price: 0,
          chooseRate: 70,
        },
        3: {
          name: '쉬머링 실버 메탈릭',
          imgUrl: '/assets/image/exterior-shimmering.png',
          carImgUrls: '/palisade/silver/image_',
          price: 0,
          chooseRate: 60,
        },
        4: {
          name: '문라이트 블루 펄',
          imgUrl: '/assets/image/exterior-moonlight.png',
          carImgUrls: '/palisade/blue/image_',
          price: 0,
          chooseRate: 50,
        },
        5: {
          name: '가이아 브라운 펄',
          imgUrl: '/assets/image/exterior-gaia.png',
          carImgUrls: '/palisade/brown/image_',
          price: 0,
          chooseRate: 40,
        },
        6: {
          name: '그라파이트 그레이 메탈릭',
          imgUrl: '/assets/image/exterior-graphite.png',
          carImgUrls: '/palisade/gray/image_',
          price: 0,
          chooseRate: 30,
        },
        7: {
          name: '로버스트 에메랄드 펄',
          imgUrl: '/assets/image/exterior-robust.png',
          carImgUrls: '/palisade/robust/image_',
          price: 40000,
          chooseRate: 70,
        },
      },
      unAvailableColors: {},
      otherTrimColors: {},
    },
    interiorColors: {
      availableColors: {
        7: {
          name: '네이비/웜그레이 투톤',
          imgUrl: '/assets/image/interior-navy_warmgray.png',
          carImgUrls: '',
          price: 0,
          chooseRate: 30,
        },
        8: {
          name: '블랙(고급)',
          imgUrl: '/assets/image/interior-premium_black.png',
          carImgUrls: '',
          price: 0,
          chooseRate: 20,
        },
        9: {
          name: '블랙원톤(블랙에디션전용)',
          imgUrl: '/assets/image/interior-onetone_black.png',
          carImgUrls: '',
          price: 0,
          chooseRate: 10,
        },
        10: {
          name: '브라운',
          imgUrl: '/assets/image/interior-brown.png',
          carImgUrls: '',
          price: 0,
          chooseRate: 5,
        },
      },
      unAvailableColors: {},
      otherTrimColors: {
        1: {
          name: '퀄팅 천연(블랙)',
          imgUrl: '/assets/image/interior-quilted.png',
          carImgUrls: '',
          price: 50000,
          chooseRate: 70,
        },
        2: {
          name: '쿨 그레이',
          imgUrl: '/assets/image/interior-coolgray.png',
          carImgUrls: '',
          price: 70000,
          chooseRate: 60,
        },
        3: {
          name: '인조가죽(블랙)',
          imgUrl: '/assets/image/interior-synthtic_black.png',
          carImgUrls: '',
          price: 50000,
          chooseRate: 40,
        },
        4: {
          name: '네이비',
          imgUrl: '/assets/image/interior-navy.png',
          carImgUrls: '',
          price: 0,
          chooseRate: 60,
        },
        5: {
          name: '블랙',
          imgUrl: '/assets/image/interior-black.png',
          carImgUrls: '',
          price: 0,
          chooseRate: 50,
        },
        6: {
          name: '버건디',
          imgUrl: '/assets/image/interior-burgundy.png',
          carImgUrls: '',
          price: 0,
          chooseRate: 40,
        },
      },
    },
  },
};

export const colors = [
  {
    trim: 'Le Blanc',
    exteriorColor: [
      {
        name: '크리미 화이트 펄',
        chooseRate: 90,
        imgUrl: Creamy,
        price: 100000,
      },
      {
        name: '어비스 블랙펄',
        chooseRate: 70,
        imgUrl: Abyss,
        price: 0,
      },
      {
        name: '쉬머링 실버 메탈릭',
        chooseRate: 60,
        imgUrl: Shimmering,
        price: 0,
      },
      {
        name: '문라이트 블루 펄',
        chooseRate: 50,
        imgUrl: Moonlight,
        price: 0,
      },
      {
        name: '가이아 브라운 펄',
        chooseRate: 40,
        imgUrl: Gaia,
        price: 0,
      },
      {
        name: '그라파이트 그레이 메탈릭',
        chooseRate: 30,
        imgUrl: Graphite,
        price: 0,
      },
    ],
    interiorColor: [
      {
        name: '퀄팅 천연(블랙)',
        chooseRate: 70,
        imgUrl: Quilted,
        price: 0,
      },
      {
        name: '쿨 그레이',
        chooseRate: 60,
        imgUrl: CoolGray,
        price: 0,
      },
    ],
    otherExteriorColor: [
      {
        trim: 'Caligraphy',
        name: '로버스트 에메랄드 펄',
        chooseRate: 70,
        imgUrl: Robust,
        price: 0,
      },
    ],
    otherInteriorColor: [
      {
        trim: 'Exclusive',
        name: '인조가죽(블랙)',
        chooseRate: 70,
        imgUrl: SyntheticBlack,
        price: 0,
      },
      {
        trim: 'Prestige',
        name: '네이비',
        chooseRate: 60,
        imgUrl: Navy,
        price: 0,
      },
      {
        trim: 'Prestige',
        name: '블랙',
        chooseRate: 50,
        imgUrl: Black,
        price: 0,
      },
      {
        trim: 'Prestige',
        name: '버건디',
        chooseRate: 40,
        imgUrl: Burgundy,
        price: 0,
      },
      {
        trim: 'Caligraphy',
        name: '네이비/웜그레이 투톤',
        chooseRate: 30,
        imgUrl: NavyWarmGray,
        price: 0,
      },
      {
        trim: 'Caligraphy',
        name: '블랙(고급)',
        chooseRate: 20,
        imgUrl: PremiumBlack,
        price: 0,
      },
      {
        trim: 'Caligraphy',
        name: '블랙원톤(블랙에디션전용)',
        chooseRate: 10,
        imgUrl: OneToneBlack,
        price: 0,
      },
      {
        trim: 'Caligraphy',
        name: '브라운',
        chooseRate: 5,
        imgUrl: Brown,
        price: 0,
      },
    ],
  },

  {
    trim: 'Exclusive',
    exteriorColor: [
      {
        name: '크리미 화이트 펄',
        chooseRate: 90,
        imgUrl: Creamy,
        price: 100000,
      },
      {
        name: '어비스 블랙펄',
        chooseRate: 70,
        imgUrl: Abyss,
        price: 0,
      },
      {
        name: '쉬머링 실버 메탈릭',
        chooseRate: 60,
        imgUrl: Shimmering,
        price: 0,
      },
      {
        name: '문라이트 블루 펄',
        chooseRate: 50,
        imgUrl: Moonlight,
        price: 0,
      },
      {
        name: '가이아 브라운 펄',
        chooseRate: 40,
        imgUrl: Gaia,
        price: 0,
      },
      {
        name: '그라파이트 그레이 메탈릭',
        chooseRate: 30,
        imgUrl: Graphite,
        price: 0,
      },
    ],
    interiorColor: [
      {
        name: '인조가죽(블랙)',
        chooseRate: 70,
        imgUrl: SyntheticBlack,
        price: 0,
      },
    ],
    otherExteriorColor: [
      {
        trim: 'Caligraphy',
        name: '로버스트 에메랄드 펄',
        chooseRate: 70,
        imgUrl: Robust,
        price: 0,
      },
    ],
    otherInteriorColor: [
      {
        trim: 'Le Blanc',
        name: '퀄팅 천연(블랙)',
        chooseRate: 70,
        imgUrl: Quilted,
        price: 0,
      },
      {
        trim: 'Le Blanc',
        name: '쿨 그레이',
        chooseRate: 60,
        imgUrl: CoolGray,
        price: 0,
      },
      {
        trim: 'Prestige',
        name: '네이비',
        chooseRate: 60,
        imgUrl: Navy,
        price: 0,
      },
      {
        trim: 'Prestige',
        name: '블랙',
        chooseRate: 50,
        imgUrl: Black,
        price: 0,
      },
      {
        trim: 'Prestige',
        name: '버건디',
        chooseRate: 40,
        imgUrl: Burgundy,
        price: 0,
      },
      {
        trim: 'Caligraphy',
        name: '네이비/웜그레이 투톤',
        chooseRate: 30,
        imgUrl: NavyWarmGray,
        price: 0,
      },
      {
        trim: 'Caligraphy',
        name: '블랙(고급)',
        chooseRate: 20,
        imgUrl: PremiumBlack,
        price: 0,
      },
      {
        trim: 'Caligraphy',
        name: '블랙원톤(블랙에디션전용)',
        chooseRate: 10,
        imgUrl: OneToneBlack,
        price: 0,
      },
      {
        trim: 'Caligraphy',
        name: '브라운',
        chooseRate: 5,
        imgUrl: Brown,
        price: 0,
      },
    ],
  },
  {
    trim: 'Prestige',
    exteriorColor: [
      {
        name: '크리미 화이트 펄',
        chooseRate: 90,
        imgUrl: Creamy,
        price: 100000,
      },
      {
        name: '어비스 블랙펄',
        chooseRate: 70,
        imgUrl: Abyss,
        price: 0,
      },
      {
        name: '쉬머링 실버 메탈릭',
        chooseRate: 60,
        imgUrl: Shimmering,
        price: 0,
      },
      {
        name: '문라이트 블루 펄',
        chooseRate: 50,
        imgUrl: Moonlight,
        price: 0,
      },
      {
        name: '가이아 브라운 펄',
        chooseRate: 40,
        imgUrl: Gaia,
        price: 0,
      },
      {
        name: '그라파이트 그레이 메탈릭',
        chooseRate: 30,
        imgUrl: Graphite,
        price: 0,
      },
    ],
    interiorColor: [
      {
        name: '네이비',
        chooseRate: 60,
        imgUrl: Navy,
        price: 0,
      },
      {
        name: '블랙',
        chooseRate: 50,
        imgUrl: Black,
        price: 0,
      },
      {
        name: '버건디',
        chooseRate: 40,
        imgUrl: Burgundy,
        price: 0,
      },
    ],
    otherExteriorColor: [
      {
        trim: 'Caligraphy',
        name: '로버스트 에메랄드 펄',
        chooseRate: 70,
        imgUrl: Robust,
        price: 0,
      },
    ],
    otherInteriorColor: [
      {
        trim: 'Le Blanc',
        name: '퀄팅 천연(블랙)',
        chooseRate: 70,
        imgUrl: Quilted,
        price: 0,
      },
      {
        trim: 'Le Blanc',
        name: '쿨 그레이',
        chooseRate: 60,
        imgUrl: CoolGray,
        price: 0,
      },
      {
        trim: 'Exclusive',
        name: '인조가죽(블랙)',
        chooseRate: 70,
        imgUrl: SyntheticBlack,
        price: 0,
      },
      {
        trim: 'Caligraphy',
        name: '네이비/웜그레이 투톤',
        chooseRate: 30,
        imgUrl: NavyWarmGray,
        price: 0,
      },
      {
        trim: 'Caligraphy',
        name: '블랙(고급)',
        chooseRate: 20,
        imgUrl: PremiumBlack,
        price: 0,
      },
      {
        trim: 'Caligraphy',
        name: '블랙원톤(블랙에디션전용)',
        chooseRate: 10,
        imgUrl: OneToneBlack,
        price: 0,
      },
      {
        trim: 'Caligraphy',
        name: '브라운',
        chooseRate: 5,
        imgUrl: Brown,
        price: 0,
      },
    ],
  },
  {
    trim: 'Caligraphy',
    exteriorColor: [
      {
        name: '크리미 화이트 펄',
        chooseRate: 90,
        imgUrl: Creamy,
        price: 100000,
      },
      {
        name: '어비스 블랙펄',
        chooseRate: 70,
        imgUrl: Abyss,
        price: 0,
      },
      {
        name: '쉬머링 실버 메탈릭',
        chooseRate: 60,
        imgUrl: Shimmering,
        price: 0,
      },
      {
        name: '문라이트 블루 펄',
        chooseRate: 50,
        imgUrl: Moonlight,
        price: 0,
      },
      {
        name: '로버스트 에메랄드 펄',
        chooseRate: 70,
        imgUrl: Robust,
        price: 0,
      },
      {
        name: '가이아 브라운 펄',
        chooseRate: 40,
        imgUrl: Gaia,
        price: 0,
      },
      {
        name: '그라파이트 그레이 메탈릭',
        chooseRate: 30,
        imgUrl: Graphite,
        price: 0,
      },
    ],
    interiorColor: [
      {
        trim: 'Caligraphy',
        name: '네이비/웜그레이 투톤',
        chooseRate: 30,
        imgUrl: NavyWarmGray,
        price: 0,
      },
      {
        trim: 'Caligraphy',
        name: '블랙(고급)',
        chooseRate: 20,
        imgUrl: PremiumBlack,
        price: 0,
      },
      {
        trim: 'Caligraphy',
        name: '블랙원톤(블랙에디션전용)',
        chooseRate: 10,
        imgUrl: OneToneBlack,
        price: 0,
      },
      {
        trim: 'Caligraphy',
        name: '브라운',
        chooseRate: 5,
        imgUrl: Brown,
        price: 0,
      },
    ],
    otehrExteriorColor: [{}],
    otherInteriorColor: [
      {
        trim: 'Le Blanc',
        name: '퀄팅 천연(블랙)',
        chooseRate: 70,
        imgUrl: Quilted,
        price: 0,
      },
      {
        trim: 'Le Blanc',
        name: '쿨 그레이',
        chooseRate: 60,
        imgUrl: CoolGray,
        price: 0,
      },
      {
        trim: 'Exclusive',
        name: '인조가죽(블랙)',
        chooseRate: 70,
        imgUrl: SyntheticBlack,
        price: 0,
      },
      {
        trim: 'Prestige',
        name: '네이비',
        chooseRate: 60,
        imgUrl: Navy,
        price: 0,
      },
      {
        trim: 'Prestige',
        name: '블랙',
        chooseRate: 50,
        imgUrl: Black,
        price: 0,
      },
      {
        trim: 'Prestige',
        name: '버건디',
        chooseRate: 40,
        imgUrl: Burgundy,
        price: 0,
      },
    ],
  },
];

export const test = {
  status: {
    code: 'SUCCESS-001',
    message: '응답 성공하였습니다.',
  },
  data: {
    exterior_color_response: {
      available_colors: [
        {
          color_id: 7,
          trim_id: 1,
          trim_name: 'Exclusive',
          name: '크리미 화이트 펄',
          img_url: 'img.make-my-car.shop/exterior/icon/WC9.jpg',
          car_img_urls: [
            'img.make-my-car.shop/exterior/car/WC9/image_001.png',
            'img.make-my-car.shop/exterior/car/WC9/image_002.png',
            'img.make-my-car.shop/exterior/car/WC9/image_003.png',
            'img.make-my-car.shop/exterior/car/WC9/image_004.png',
            'img.make-my-car.shop/exterior/car/WC9/image_005.png',
            'img.make-my-car.shop/exterior/car/WC9/image_006.png',
            'img.make-my-car.shop/exterior/car/WC9/image_007.png',
            'img.make-my-car.shop/exterior/car/WC9/image_008.png',
            'img.make-my-car.shop/exterior/car/WC9/image_009.png',
            'img.make-my-car.shop/exterior/car/WC9/image_010.png',
            'img.make-my-car.shop/exterior/car/WC9/image_011.png',
            'img.make-my-car.shop/exterior/car/WC9/image_012.png',
            'img.make-my-car.shop/exterior/car/WC9/image_013.png',
            'img.make-my-car.shop/exterior/car/WC9/image_014.png',
            'img.make-my-car.shop/exterior/car/WC9/image_015.png',
            'img.make-my-car.shop/exterior/car/WC9/image_016.png',
            'img.make-my-car.shop/exterior/car/WC9/image_017.png',
            'img.make-my-car.shop/exterior/car/WC9/image_018.png',
            'img.make-my-car.shop/exterior/car/WC9/image_019.png',
            'img.make-my-car.shop/exterior/car/WC9/image_020.png',
            'img.make-my-car.shop/exterior/car/WC9/image_021.png',
            'img.make-my-car.shop/exterior/car/WC9/image_022.png',
            'img.make-my-car.shop/exterior/car/WC9/image_023.png',
            'img.make-my-car.shop/exterior/car/WC9/image_024.png',
            'img.make-my-car.shop/exterior/car/WC9/image_025.png',
            'img.make-my-car.shop/exterior/car/WC9/image_026.png',
            'img.make-my-car.shop/exterior/car/WC9/image_027.png',
            'img.make-my-car.shop/exterior/car/WC9/image_028.png',
            'img.make-my-car.shop/exterior/car/WC9/image_029.png',
            'img.make-my-car.shop/exterior/car/WC9/image_030.png',
            'img.make-my-car.shop/exterior/car/WC9/image_031.png',
            'img.make-my-car.shop/exterior/car/WC9/image_032.png',
            'img.make-my-car.shop/exterior/car/WC9/image_033.png',
            'img.make-my-car.shop/exterior/car/WC9/image_034.png',
            'img.make-my-car.shop/exterior/car/WC9/image_035.png',
            'img.make-my-car.shop/exterior/car/WC9/image_036.png',
            'img.make-my-car.shop/exterior/car/WC9/image_037.png',
            'img.make-my-car.shop/exterior/car/WC9/image_038.png',
            'img.make-my-car.shop/exterior/car/WC9/image_039.png',
            'img.make-my-car.shop/exterior/car/WC9/image_040.png',
            'img.make-my-car.shop/exterior/car/WC9/image_041.png',
            'img.make-my-car.shop/exterior/car/WC9/image_042.png',
            'img.make-my-car.shop/exterior/car/WC9/image_043.png',
            'img.make-my-car.shop/exterior/car/WC9/image_044.png',
            'img.make-my-car.shop/exterior/car/WC9/image_045.png',
            'img.make-my-car.shop/exterior/car/WC9/image_046.png',
            'img.make-my-car.shop/exterior/car/WC9/image_047.png',
            'img.make-my-car.shop/exterior/car/WC9/image_048.png',
            'img.make-my-car.shop/exterior/car/WC9/image_049.png',
            'img.make-my-car.shop/exterior/car/WC9/image_050.png',
            'img.make-my-car.shop/exterior/car/WC9/image_051.png',
            'img.make-my-car.shop/exterior/car/WC9/image_052.png',
            'img.make-my-car.shop/exterior/car/WC9/image_053.png',
            'img.make-my-car.shop/exterior/car/WC9/image_054.png',
            'img.make-my-car.shop/exterior/car/WC9/image_055.png',
            'img.make-my-car.shop/exterior/car/WC9/image_056.png',
            'img.make-my-car.shop/exterior/car/WC9/image_057.png',
            'img.make-my-car.shop/exterior/car/WC9/image_058.png',
            'img.make-my-car.shop/exterior/car/WC9/image_059.png',
            'img.make-my-car.shop/exterior/car/WC9/image_060.png',
          ],
          price: 100000,
          choose_rate: 75,
        },
        {
          color_id: 1,
          trim_id: 1,
          trim_name: 'Exclusive',
          name: '어비스블랙펄',
          img_url: 'img.make-my-car.shop/exterior/icon/A2B.jpg',
          car_img_urls: [
            'img.make-my-car.shop/exterior/car/A2B/image_001.png',
            'img.make-my-car.shop/exterior/car/A2B/image_002.png',
            'img.make-my-car.shop/exterior/car/A2B/image_003.png',
            'img.make-my-car.shop/exterior/car/A2B/image_004.png',
            'img.make-my-car.shop/exterior/car/A2B/image_005.png',
            'img.make-my-car.shop/exterior/car/A2B/image_006.png',
            'img.make-my-car.shop/exterior/car/A2B/image_007.png',
            'img.make-my-car.shop/exterior/car/A2B/image_008.png',
            'img.make-my-car.shop/exterior/car/A2B/image_009.png',
            'img.make-my-car.shop/exterior/car/A2B/image_010.png',
            'img.make-my-car.shop/exterior/car/A2B/image_011.png',
            'img.make-my-car.shop/exterior/car/A2B/image_012.png',
            'img.make-my-car.shop/exterior/car/A2B/image_013.png',
            'img.make-my-car.shop/exterior/car/A2B/image_014.png',
            'img.make-my-car.shop/exterior/car/A2B/image_015.png',
            'img.make-my-car.shop/exterior/car/A2B/image_016.png',
            'img.make-my-car.shop/exterior/car/A2B/image_017.png',
            'img.make-my-car.shop/exterior/car/A2B/image_018.png',
            'img.make-my-car.shop/exterior/car/A2B/image_019.png',
            'img.make-my-car.shop/exterior/car/A2B/image_020.png',
            'img.make-my-car.shop/exterior/car/A2B/image_021.png',
            'img.make-my-car.shop/exterior/car/A2B/image_022.png',
            'img.make-my-car.shop/exterior/car/A2B/image_023.png',
            'img.make-my-car.shop/exterior/car/A2B/image_024.png',
            'img.make-my-car.shop/exterior/car/A2B/image_025.png',
            'img.make-my-car.shop/exterior/car/A2B/image_026.png',
            'img.make-my-car.shop/exterior/car/A2B/image_027.png',
            'img.make-my-car.shop/exterior/car/A2B/image_028.png',
            'img.make-my-car.shop/exterior/car/A2B/image_029.png',
            'img.make-my-car.shop/exterior/car/A2B/image_030.png',
            'img.make-my-car.shop/exterior/car/A2B/image_031.png',
            'img.make-my-car.shop/exterior/car/A2B/image_032.png',
            'img.make-my-car.shop/exterior/car/A2B/image_033.png',
            'img.make-my-car.shop/exterior/car/A2B/image_034.png',
            'img.make-my-car.shop/exterior/car/A2B/image_035.png',
            'img.make-my-car.shop/exterior/car/A2B/image_036.png',
            'img.make-my-car.shop/exterior/car/A2B/image_037.png',
            'img.make-my-car.shop/exterior/car/A2B/image_038.png',
            'img.make-my-car.shop/exterior/car/A2B/image_039.png',
            'img.make-my-car.shop/exterior/car/A2B/image_040.png',
            'img.make-my-car.shop/exterior/car/A2B/image_041.png',
            'img.make-my-car.shop/exterior/car/A2B/image_042.png',
            'img.make-my-car.shop/exterior/car/A2B/image_043.png',
            'img.make-my-car.shop/exterior/car/A2B/image_044.png',
            'img.make-my-car.shop/exterior/car/A2B/image_045.png',
            'img.make-my-car.shop/exterior/car/A2B/image_046.png',
            'img.make-my-car.shop/exterior/car/A2B/image_047.png',
            'img.make-my-car.shop/exterior/car/A2B/image_048.png',
            'img.make-my-car.shop/exterior/car/A2B/image_049.png',
            'img.make-my-car.shop/exterior/car/A2B/image_050.png',
            'img.make-my-car.shop/exterior/car/A2B/image_051.png',
            'img.make-my-car.shop/exterior/car/A2B/image_052.png',
            'img.make-my-car.shop/exterior/car/A2B/image_053.png',
            'img.make-my-car.shop/exterior/car/A2B/image_054.png',
            'img.make-my-car.shop/exterior/car/A2B/image_055.png',
            'img.make-my-car.shop/exterior/car/A2B/image_056.png',
            'img.make-my-car.shop/exterior/car/A2B/image_057.png',
            'img.make-my-car.shop/exterior/car/A2B/image_058.png',
            'img.make-my-car.shop/exterior/car/A2B/image_059.png',
            'img.make-my-car.shop/exterior/car/A2B/image_060.png',
          ],
          price: 0,
          choose_rate: 70,
        },
        {
          color_id: 6,
          trim_id: 1,
          trim_name: 'Exclusive',
          name: '그라파이트 그레이 메탈릭',
          img_url: 'img.make-my-car.shop/exterior/icon/P7V.jpg',
          car_img_urls: [
            'img.make-my-car.shop/exterior/car/P7V/image_001.png',
            'img.make-my-car.shop/exterior/car/P7V/image_002.png',
            'img.make-my-car.shop/exterior/car/P7V/image_003.png',
            'img.make-my-car.shop/exterior/car/P7V/image_004.png',
            'img.make-my-car.shop/exterior/car/P7V/image_005.png',
            'img.make-my-car.shop/exterior/car/P7V/image_006.png',
            'img.make-my-car.shop/exterior/car/P7V/image_007.png',
            'img.make-my-car.shop/exterior/car/P7V/image_008.png',
            'img.make-my-car.shop/exterior/car/P7V/image_009.png',
            'img.make-my-car.shop/exterior/car/P7V/image_010.png',
            'img.make-my-car.shop/exterior/car/P7V/image_011.png',
            'img.make-my-car.shop/exterior/car/P7V/image_012.png',
            'img.make-my-car.shop/exterior/car/P7V/image_013.png',
            'img.make-my-car.shop/exterior/car/P7V/image_014.png',
            'img.make-my-car.shop/exterior/car/P7V/image_015.png',
            'img.make-my-car.shop/exterior/car/P7V/image_016.png',
            'img.make-my-car.shop/exterior/car/P7V/image_017.png',
            'img.make-my-car.shop/exterior/car/P7V/image_018.png',
            'img.make-my-car.shop/exterior/car/P7V/image_019.png',
            'img.make-my-car.shop/exterior/car/P7V/image_020.png',
            'img.make-my-car.shop/exterior/car/P7V/image_021.png',
            'img.make-my-car.shop/exterior/car/P7V/image_022.png',
            'img.make-my-car.shop/exterior/car/P7V/image_023.png',
            'img.make-my-car.shop/exterior/car/P7V/image_024.png',
            'img.make-my-car.shop/exterior/car/P7V/image_025.png',
            'img.make-my-car.shop/exterior/car/P7V/image_026.png',
            'img.make-my-car.shop/exterior/car/P7V/image_027.png',
            'img.make-my-car.shop/exterior/car/P7V/image_028.png',
            'img.make-my-car.shop/exterior/car/P7V/image_029.png',
            'img.make-my-car.shop/exterior/car/P7V/image_030.png',
            'img.make-my-car.shop/exterior/car/P7V/image_031.png',
            'img.make-my-car.shop/exterior/car/P7V/image_032.png',
            'img.make-my-car.shop/exterior/car/P7V/image_033.png',
            'img.make-my-car.shop/exterior/car/P7V/image_034.png',
            'img.make-my-car.shop/exterior/car/P7V/image_035.png',
            'img.make-my-car.shop/exterior/car/P7V/image_036.png',
            'img.make-my-car.shop/exterior/car/P7V/image_037.png',
            'img.make-my-car.shop/exterior/car/P7V/image_038.png',
            'img.make-my-car.shop/exterior/car/P7V/image_039.png',
            'img.make-my-car.shop/exterior/car/P7V/image_040.png',
            'img.make-my-car.shop/exterior/car/P7V/image_041.png',
            'img.make-my-car.shop/exterior/car/P7V/image_042.png',
            'img.make-my-car.shop/exterior/car/P7V/image_043.png',
            'img.make-my-car.shop/exterior/car/P7V/image_044.png',
            'img.make-my-car.shop/exterior/car/P7V/image_045.png',
            'img.make-my-car.shop/exterior/car/P7V/image_046.png',
            'img.make-my-car.shop/exterior/car/P7V/image_047.png',
            'img.make-my-car.shop/exterior/car/P7V/image_048.png',
            'img.make-my-car.shop/exterior/car/P7V/image_049.png',
            'img.make-my-car.shop/exterior/car/P7V/image_050.png',
            'img.make-my-car.shop/exterior/car/P7V/image_051.png',
            'img.make-my-car.shop/exterior/car/P7V/image_052.png',
            'img.make-my-car.shop/exterior/car/P7V/image_053.png',
            'img.make-my-car.shop/exterior/car/P7V/image_054.png',
            'img.make-my-car.shop/exterior/car/P7V/image_055.png',
            'img.make-my-car.shop/exterior/car/P7V/image_056.png',
            'img.make-my-car.shop/exterior/car/P7V/image_057.png',
            'img.make-my-car.shop/exterior/car/P7V/image_058.png',
            'img.make-my-car.shop/exterior/car/P7V/image_059.png',
            'img.make-my-car.shop/exterior/car/P7V/image_060.png',
          ],
          price: 0,
          choose_rate: 60,
        },
        {
          color_id: 2,
          trim_id: 1,
          trim_name: 'Exclusive',
          name: '쉬머링 실버 메탈릭',
          img_url: 'img.make-my-car.shop/exterior/icon/R2T.jpg',
          car_img_urls: [
            'img.make-my-car.shop/exterior/car/R2T/image_001.png',
            'img.make-my-car.shop/exterior/car/R2T/image_002.png',
            'img.make-my-car.shop/exterior/car/R2T/image_003.png',
            'img.make-my-car.shop/exterior/car/R2T/image_004.png',
            'img.make-my-car.shop/exterior/car/R2T/image_005.png',
            'img.make-my-car.shop/exterior/car/R2T/image_006.png',
            'img.make-my-car.shop/exterior/car/R2T/image_007.png',
            'img.make-my-car.shop/exterior/car/R2T/image_008.png',
            'img.make-my-car.shop/exterior/car/R2T/image_009.png',
            'img.make-my-car.shop/exterior/car/R2T/image_010.png',
            'img.make-my-car.shop/exterior/car/R2T/image_011.png',
            'img.make-my-car.shop/exterior/car/R2T/image_012.png',
            'img.make-my-car.shop/exterior/car/R2T/image_013.png',
            'img.make-my-car.shop/exterior/car/R2T/image_014.png',
            'img.make-my-car.shop/exterior/car/R2T/image_015.png',
            'img.make-my-car.shop/exterior/car/R2T/image_016.png',
            'img.make-my-car.shop/exterior/car/R2T/image_017.png',
            'img.make-my-car.shop/exterior/car/R2T/image_018.png',
            'img.make-my-car.shop/exterior/car/R2T/image_019.png',
            'img.make-my-car.shop/exterior/car/R2T/image_020.png',
            'img.make-my-car.shop/exterior/car/R2T/image_021.png',
            'img.make-my-car.shop/exterior/car/R2T/image_022.png',
            'img.make-my-car.shop/exterior/car/R2T/image_023.png',
            'img.make-my-car.shop/exterior/car/R2T/image_024.png',
            'img.make-my-car.shop/exterior/car/R2T/image_025.png',
            'img.make-my-car.shop/exterior/car/R2T/image_026.png',
            'img.make-my-car.shop/exterior/car/R2T/image_027.png',
            'img.make-my-car.shop/exterior/car/R2T/image_028.png',
            'img.make-my-car.shop/exterior/car/R2T/image_029.png',
            'img.make-my-car.shop/exterior/car/R2T/image_030.png',
            'img.make-my-car.shop/exterior/car/R2T/image_031.png',
            'img.make-my-car.shop/exterior/car/R2T/image_032.png',
            'img.make-my-car.shop/exterior/car/R2T/image_033.png',
            'img.make-my-car.shop/exterior/car/R2T/image_034.png',
            'img.make-my-car.shop/exterior/car/R2T/image_035.png',
            'img.make-my-car.shop/exterior/car/R2T/image_036.png',
            'img.make-my-car.shop/exterior/car/R2T/image_037.png',
            'img.make-my-car.shop/exterior/car/R2T/image_038.png',
            'img.make-my-car.shop/exterior/car/R2T/image_039.png',
            'img.make-my-car.shop/exterior/car/R2T/image_040.png',
            'img.make-my-car.shop/exterior/car/R2T/image_041.png',
            'img.make-my-car.shop/exterior/car/R2T/image_042.png',
            'img.make-my-car.shop/exterior/car/R2T/image_043.png',
            'img.make-my-car.shop/exterior/car/R2T/image_044.png',
            'img.make-my-car.shop/exterior/car/R2T/image_045.png',
            'img.make-my-car.shop/exterior/car/R2T/image_046.png',
            'img.make-my-car.shop/exterior/car/R2T/image_047.png',
            'img.make-my-car.shop/exterior/car/R2T/image_048.png',
            'img.make-my-car.shop/exterior/car/R2T/image_049.png',
            'img.make-my-car.shop/exterior/car/R2T/image_050.png',
            'img.make-my-car.shop/exterior/car/R2T/image_051.png',
            'img.make-my-car.shop/exterior/car/R2T/image_052.png',
            'img.make-my-car.shop/exterior/car/R2T/image_053.png',
            'img.make-my-car.shop/exterior/car/R2T/image_054.png',
            'img.make-my-car.shop/exterior/car/R2T/image_055.png',
            'img.make-my-car.shop/exterior/car/R2T/image_056.png',
            'img.make-my-car.shop/exterior/car/R2T/image_057.png',
            'img.make-my-car.shop/exterior/car/R2T/image_058.png',
            'img.make-my-car.shop/exterior/car/R2T/image_059.png',
            'img.make-my-car.shop/exterior/car/R2T/image_060.png',
          ],
          price: 0,
          choose_rate: 40,
        },
        {
          color_id: 4,
          trim_id: 1,
          trim_name: 'Exclusive',
          name: '문라이트 블루 펄',
          img_url: 'img.make-my-car.shop/exterior/icon/UB7.jpg',
          car_img_urls: [
            'img.make-my-car.shop/exterior/car/UB7/image_001.png',
            'img.make-my-car.shop/exterior/car/UB7/image_002.png',
            'img.make-my-car.shop/exterior/car/UB7/image_003.png',
            'img.make-my-car.shop/exterior/car/UB7/image_004.png',
            'img.make-my-car.shop/exterior/car/UB7/image_005.png',
            'img.make-my-car.shop/exterior/car/UB7/image_006.png',
            'img.make-my-car.shop/exterior/car/UB7/image_007.png',
            'img.make-my-car.shop/exterior/car/UB7/image_008.png',
            'img.make-my-car.shop/exterior/car/UB7/image_009.png',
            'img.make-my-car.shop/exterior/car/UB7/image_010.png',
            'img.make-my-car.shop/exterior/car/UB7/image_011.png',
            'img.make-my-car.shop/exterior/car/UB7/image_012.png',
            'img.make-my-car.shop/exterior/car/UB7/image_013.png',
            'img.make-my-car.shop/exterior/car/UB7/image_014.png',
            'img.make-my-car.shop/exterior/car/UB7/image_015.png',
            'img.make-my-car.shop/exterior/car/UB7/image_016.png',
            'img.make-my-car.shop/exterior/car/UB7/image_017.png',
            'img.make-my-car.shop/exterior/car/UB7/image_018.png',
            'img.make-my-car.shop/exterior/car/UB7/image_019.png',
            'img.make-my-car.shop/exterior/car/UB7/image_020.png',
            'img.make-my-car.shop/exterior/car/UB7/image_021.png',
            'img.make-my-car.shop/exterior/car/UB7/image_022.png',
            'img.make-my-car.shop/exterior/car/UB7/image_023.png',
            'img.make-my-car.shop/exterior/car/UB7/image_024.png',
            'img.make-my-car.shop/exterior/car/UB7/image_025.png',
            'img.make-my-car.shop/exterior/car/UB7/image_026.png',
            'img.make-my-car.shop/exterior/car/UB7/image_027.png',
            'img.make-my-car.shop/exterior/car/UB7/image_028.png',
            'img.make-my-car.shop/exterior/car/UB7/image_029.png',
            'img.make-my-car.shop/exterior/car/UB7/image_030.png',
            'img.make-my-car.shop/exterior/car/UB7/image_031.png',
            'img.make-my-car.shop/exterior/car/UB7/image_032.png',
            'img.make-my-car.shop/exterior/car/UB7/image_033.png',
            'img.make-my-car.shop/exterior/car/UB7/image_034.png',
            'img.make-my-car.shop/exterior/car/UB7/image_035.png',
            'img.make-my-car.shop/exterior/car/UB7/image_036.png',
            'img.make-my-car.shop/exterior/car/UB7/image_037.png',
            'img.make-my-car.shop/exterior/car/UB7/image_038.png',
            'img.make-my-car.shop/exterior/car/UB7/image_039.png',
            'img.make-my-car.shop/exterior/car/UB7/image_040.png',
            'img.make-my-car.shop/exterior/car/UB7/image_041.png',
            'img.make-my-car.shop/exterior/car/UB7/image_042.png',
            'img.make-my-car.shop/exterior/car/UB7/image_043.png',
            'img.make-my-car.shop/exterior/car/UB7/image_044.png',
            'img.make-my-car.shop/exterior/car/UB7/image_045.png',
            'img.make-my-car.shop/exterior/car/UB7/image_046.png',
            'img.make-my-car.shop/exterior/car/UB7/image_047.png',
            'img.make-my-car.shop/exterior/car/UB7/image_048.png',
            'img.make-my-car.shop/exterior/car/UB7/image_049.png',
            'img.make-my-car.shop/exterior/car/UB7/image_050.png',
            'img.make-my-car.shop/exterior/car/UB7/image_051.png',
            'img.make-my-car.shop/exterior/car/UB7/image_052.png',
            'img.make-my-car.shop/exterior/car/UB7/image_053.png',
            'img.make-my-car.shop/exterior/car/UB7/image_054.png',
            'img.make-my-car.shop/exterior/car/UB7/image_055.png',
            'img.make-my-car.shop/exterior/car/UB7/image_056.png',
            'img.make-my-car.shop/exterior/car/UB7/image_057.png',
            'img.make-my-car.shop/exterior/car/UB7/image_058.png',
            'img.make-my-car.shop/exterior/car/UB7/image_059.png',
            'img.make-my-car.shop/exterior/car/UB7/image_060.png',
          ],
          price: 0,
          choose_rate: 30,
        },
        {
          color_id: 5,
          trim_id: 1,
          trim_name: 'Exclusive',
          name: '가이아 블라운 펄',
          img_url: 'img.make-my-car.shop/exterior/icon/D2S.jpg',
          car_img_urls: [
            'img.make-my-car.shop/exterior/car/D2S/image_001.png',
            'img.make-my-car.shop/exterior/car/D2S/image_002.png',
            'img.make-my-car.shop/exterior/car/D2S/image_003.png',
            'img.make-my-car.shop/exterior/car/D2S/image_004.png',
            'img.make-my-car.shop/exterior/car/D2S/image_005.png',
            'img.make-my-car.shop/exterior/car/D2S/image_006.png',
            'img.make-my-car.shop/exterior/car/D2S/image_007.png',
            'img.make-my-car.shop/exterior/car/D2S/image_008.png',
            'img.make-my-car.shop/exterior/car/D2S/image_009.png',
            'img.make-my-car.shop/exterior/car/D2S/image_010.png',
            'img.make-my-car.shop/exterior/car/D2S/image_011.png',
            'img.make-my-car.shop/exterior/car/D2S/image_012.png',
            'img.make-my-car.shop/exterior/car/D2S/image_013.png',
            'img.make-my-car.shop/exterior/car/D2S/image_014.png',
            'img.make-my-car.shop/exterior/car/D2S/image_015.png',
            'img.make-my-car.shop/exterior/car/D2S/image_016.png',
            'img.make-my-car.shop/exterior/car/D2S/image_017.png',
            'img.make-my-car.shop/exterior/car/D2S/image_018.png',
            'img.make-my-car.shop/exterior/car/D2S/image_019.png',
            'img.make-my-car.shop/exterior/car/D2S/image_020.png',
            'img.make-my-car.shop/exterior/car/D2S/image_021.png',
            'img.make-my-car.shop/exterior/car/D2S/image_022.png',
            'img.make-my-car.shop/exterior/car/D2S/image_023.png',
            'img.make-my-car.shop/exterior/car/D2S/image_024.png',
            'img.make-my-car.shop/exterior/car/D2S/image_025.png',
            'img.make-my-car.shop/exterior/car/D2S/image_026.png',
            'img.make-my-car.shop/exterior/car/D2S/image_027.png',
            'img.make-my-car.shop/exterior/car/D2S/image_028.png',
            'img.make-my-car.shop/exterior/car/D2S/image_029.png',
            'img.make-my-car.shop/exterior/car/D2S/image_030.png',
            'img.make-my-car.shop/exterior/car/D2S/image_031.png',
            'img.make-my-car.shop/exterior/car/D2S/image_032.png',
            'img.make-my-car.shop/exterior/car/D2S/image_033.png',
            'img.make-my-car.shop/exterior/car/D2S/image_034.png',
            'img.make-my-car.shop/exterior/car/D2S/image_035.png',
            'img.make-my-car.shop/exterior/car/D2S/image_036.png',
            'img.make-my-car.shop/exterior/car/D2S/image_037.png',
            'img.make-my-car.shop/exterior/car/D2S/image_038.png',
            'img.make-my-car.shop/exterior/car/D2S/image_039.png',
            'img.make-my-car.shop/exterior/car/D2S/image_040.png',
            'img.make-my-car.shop/exterior/car/D2S/image_041.png',
            'img.make-my-car.shop/exterior/car/D2S/image_042.png',
            'img.make-my-car.shop/exterior/car/D2S/image_043.png',
            'img.make-my-car.shop/exterior/car/D2S/image_044.png',
            'img.make-my-car.shop/exterior/car/D2S/image_045.png',
            'img.make-my-car.shop/exterior/car/D2S/image_046.png',
            'img.make-my-car.shop/exterior/car/D2S/image_047.png',
            'img.make-my-car.shop/exterior/car/D2S/image_048.png',
            'img.make-my-car.shop/exterior/car/D2S/image_049.png',
            'img.make-my-car.shop/exterior/car/D2S/image_050.png',
            'img.make-my-car.shop/exterior/car/D2S/image_051.png',
            'img.make-my-car.shop/exterior/car/D2S/image_052.png',
            'img.make-my-car.shop/exterior/car/D2S/image_053.png',
            'img.make-my-car.shop/exterior/car/D2S/image_054.png',
            'img.make-my-car.shop/exterior/car/D2S/image_055.png',
            'img.make-my-car.shop/exterior/car/D2S/image_056.png',
            'img.make-my-car.shop/exterior/car/D2S/image_057.png',
            'img.make-my-car.shop/exterior/car/D2S/image_058.png',
            'img.make-my-car.shop/exterior/car/D2S/image_059.png',
            'img.make-my-car.shop/exterior/car/D2S/image_060.png',
          ],
          price: 0,
          choose_rate: 20,
        },
      ],
      unavailable_colors: [],
      other_trim_colors: [
        {
          color_id: 3,
          trim_id: 4,
          trim_name: 'Caligraphy',
          name: '로버스트 에메랄드 펄',
          img_url: 'img.make-my-car.shop/exterior/icon/R8N.jpg',
          car_img_urls: [
            'img.make-my-car.shop/exterior/car/R8N/image_001.png',
            'img.make-my-car.shop/exterior/car/R8N/image_002.png',
            'img.make-my-car.shop/exterior/car/R8N/image_003.png',
            'img.make-my-car.shop/exterior/car/R8N/image_004.png',
            'img.make-my-car.shop/exterior/car/R8N/image_005.png',
            'img.make-my-car.shop/exterior/car/R8N/image_006.png',
            'img.make-my-car.shop/exterior/car/R8N/image_007.png',
            'img.make-my-car.shop/exterior/car/R8N/image_008.png',
            'img.make-my-car.shop/exterior/car/R8N/image_009.png',
            'img.make-my-car.shop/exterior/car/R8N/image_010.png',
            'img.make-my-car.shop/exterior/car/R8N/image_011.png',
            'img.make-my-car.shop/exterior/car/R8N/image_012.png',
            'img.make-my-car.shop/exterior/car/R8N/image_013.png',
            'img.make-my-car.shop/exterior/car/R8N/image_014.png',
            'img.make-my-car.shop/exterior/car/R8N/image_015.png',
            'img.make-my-car.shop/exterior/car/R8N/image_016.png',
            'img.make-my-car.shop/exterior/car/R8N/image_017.png',
            'img.make-my-car.shop/exterior/car/R8N/image_018.png',
            'img.make-my-car.shop/exterior/car/R8N/image_019.png',
            'img.make-my-car.shop/exterior/car/R8N/image_020.png',
            'img.make-my-car.shop/exterior/car/R8N/image_021.png',
            'img.make-my-car.shop/exterior/car/R8N/image_022.png',
            'img.make-my-car.shop/exterior/car/R8N/image_023.png',
            'img.make-my-car.shop/exterior/car/R8N/image_024.png',
            'img.make-my-car.shop/exterior/car/R8N/image_025.png',
            'img.make-my-car.shop/exterior/car/R8N/image_026.png',
            'img.make-my-car.shop/exterior/car/R8N/image_027.png',
            'img.make-my-car.shop/exterior/car/R8N/image_028.png',
            'img.make-my-car.shop/exterior/car/R8N/image_029.png',
            'img.make-my-car.shop/exterior/car/R8N/image_030.png',
            'img.make-my-car.shop/exterior/car/R8N/image_031.png',
            'img.make-my-car.shop/exterior/car/R8N/image_032.png',
            'img.make-my-car.shop/exterior/car/R8N/image_033.png',
            'img.make-my-car.shop/exterior/car/R8N/image_034.png',
            'img.make-my-car.shop/exterior/car/R8N/image_035.png',
            'img.make-my-car.shop/exterior/car/R8N/image_036.png',
            'img.make-my-car.shop/exterior/car/R8N/image_037.png',
            'img.make-my-car.shop/exterior/car/R8N/image_038.png',
            'img.make-my-car.shop/exterior/car/R8N/image_039.png',
            'img.make-my-car.shop/exterior/car/R8N/image_040.png',
            'img.make-my-car.shop/exterior/car/R8N/image_041.png',
            'img.make-my-car.shop/exterior/car/R8N/image_042.png',
            'img.make-my-car.shop/exterior/car/R8N/image_043.png',
            'img.make-my-car.shop/exterior/car/R8N/image_044.png',
            'img.make-my-car.shop/exterior/car/R8N/image_045.png',
            'img.make-my-car.shop/exterior/car/R8N/image_046.png',
            'img.make-my-car.shop/exterior/car/R8N/image_047.png',
            'img.make-my-car.shop/exterior/car/R8N/image_048.png',
            'img.make-my-car.shop/exterior/car/R8N/image_049.png',
            'img.make-my-car.shop/exterior/car/R8N/image_050.png',
            'img.make-my-car.shop/exterior/car/R8N/image_051.png',
            'img.make-my-car.shop/exterior/car/R8N/image_052.png',
            'img.make-my-car.shop/exterior/car/R8N/image_053.png',
            'img.make-my-car.shop/exterior/car/R8N/image_054.png',
            'img.make-my-car.shop/exterior/car/R8N/image_055.png',
            'img.make-my-car.shop/exterior/car/R8N/image_056.png',
            'img.make-my-car.shop/exterior/car/R8N/image_057.png',
            'img.make-my-car.shop/exterior/car/R8N/image_058.png',
            'img.make-my-car.shop/exterior/car/R8N/image_059.png',
            'img.make-my-car.shop/exterior/car/R8N/image_060.png',
          ],
          price: 0,
          choose_rate: 40,
        },
      ],
    },
    interior_color_response: {
      available_colors: [
        {
          color_id: 4,
          trim_id: 1,
          trim_name: 'Exclusive',
          name: '퀄팅천연(블랙)',
          img_url: 'img.make-my-car.shop/interior/icon/I49.jpg',
          car_img_url: 'img.make-my-car.shop/interior/car/I49.jpg',
          price: 0,
          choose_rate: 40,
        },
        {
          color_id: 5,
          trim_id: 1,
          trim_name: 'Exclusive',
          name: '인조가죽(블랙)',
          img_url: 'img.make-my-car.shop/interior/icon/I50.jpg',
          car_img_url: 'img.make-my-car.shop/interior/car/I50.jpg',
          price: 0,
          choose_rate: 30,
        },
      ],
      unavailable_colors: [],
      other_trim_colors: [
        {
          color_id: 3,
          trim_id: 4,
          trim_name: 'Caligraphy',
          name: '네이비/웜그레이 투톤',
          img_url: 'img.make-my-car.shop/interior/icon/WDX.jpg',
          car_img_url: 'img.make-my-car.shop/interior/car/WDX.jpg',
          price: 0,
          choose_rate: 70,
        },
        {
          color_id: 6,
          trim_id: 4,
          trim_name: 'Caligraphy',
          name: '블랙원톤(블랙에디션 전용)',
          img_url: 'img.make-my-car.shop/interior/icon/NKE.jpg',
          car_img_url: 'img.make-my-car.shop/interior/car/NKE.jpg',
          price: 0,
          choose_rate: 70,
        },
        {
          color_id: 2,
          trim_id: 4,
          trim_name: 'Caligraphy',
          name: '브라운',
          img_url: 'img.make-my-car.shop/interior/icon/RNT.jpg',
          car_img_url: 'img.make-my-car.shop/interior/car/RNT.jpg',
          price: 0,
          choose_rate: 60,
        },
        {
          color_id: 8,
          trim_id: 3,
          trim_name: 'Prestige',
          name: '블랙',
          img_url: 'img.make-my-car.shop/interior/icon/WFW.jpg',
          car_img_url: 'img.make-my-car.shop/interior/car/WFW.jpg',
          price: 0,
          choose_rate: 60,
        },
        {
          color_id: 1,
          trim_id: 4,
          trim_name: 'Caligraphy',
          name: '블랙(고급)',
          img_url: 'img.make-my-car.shop/interior/icon/NBX.jpg',
          car_img_url: 'img.make-my-car.shop/interior/car/NBX.jpg',
          price: 0,
          choose_rate: 50,
        },
        {
          color_id: 10,
          trim_id: 2,
          trim_name: 'Le Blanc',
          name: '쿨그레이',
          img_url: 'img.make-my-car.shop/interior/icon/YJY.jpg',
          car_img_url: 'img.make-my-car.shop/interior/car/YJY.jpg',
          price: 0,
          choose_rate: 50,
        },
        {
          color_id: 7,
          trim_id: 3,
          trim_name: 'Prestige',
          name: '네이비',
          img_url: 'img.make-my-car.shop/interior/icon/WDN.jpg',
          car_img_url: 'img.make-my-car.shop/interior/car/WDN.jpg',
          price: 0,
          choose_rate: 30,
        },
        {
          color_id: 9,
          trim_id: 3,
          trim_name: 'Prestige',
          name: '버건디',
          img_url: 'img.make-my-car.shop/interior/icon/WNX.jpg',
          car_img_url: 'img.make-my-car.shop/interior/car/WNX.jpg',
          price: 0,
          choose_rate: 30,
        },
      ],
    },
  },
};
